// Builds src/tokens/tokens.css and src/tokens/tokens.ts from the token JSON files.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
// Same contrast code the workbench uses (Node 22.18+ runs .ts imports directly).
import { contrastRatio, contrastThreshold } from '../src/lib/contrast.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'tokens');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const primitives = read('primitives.json');
const semantic = read('semantic.json');
const themeFiles = readdirSync(join(root, 'themes')).filter((f) => f.endsWith('.json')).sort();
const themes = themeFiles.map((f) => read(join('themes', f)));

const flat = {};
(function walk(obj, path) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    const p = [...path, k];
    if (v && typeof v === 'object') walk(v, p);
    else flat[p.join('.')] = String(v);
  }
})(primitives, []);

const cssName = (name) => name.replace(/\./g, '-');
const primVar = (path) => `--wl-p-${cssName(path)}`;
const semVar = (name) => `--wl-${cssName(name)}`;
const REF = /^\{([^}]+)\}$/;

function toCss(value, where) {
  const m = REF.exec(value);
  if (!m) return value;
  if (!(m[1] in flat)) throw new Error(`${where}: unknown primitive ${value}`);
  return `var(${primVar(m[1])})`;
}
function resolve(value, where) {
  const m = REF.exec(value);
  if (!m) return value;
  if (!(m[1] in flat)) throw new Error(`${where}: unknown primitive ${value}`);
  return flat[m[1]];
}

const names = Object.keys(semantic.tokens);
for (const t of themes) {
  for (const k of Object.keys(t.tokens)) {
    if (!names.includes(k)) throw new Error(`theme ${t.name}: unknown semantic token ${k}`);
  }
}

let css = '/* Generated by scripts/build-tokens.mjs. Do not edit. */\n:root {\n';
for (const [p, v] of Object.entries(flat)) css += `  ${primVar(p)}: ${v};\n`;
for (const n of names) css += `  ${semVar(n)}: ${toCss(semantic.tokens[n].value, n)};\n`;
css += '}\n';
for (const t of themes) {
  css += `\n[data-theme="${t.name}"] {\n`;
  for (const [n, v] of Object.entries(t.tokens)) css += `  ${semVar(n)}: ${toCss(v, `${t.name}.${n}`)};\n`;
  css += '}\n';
}
css += '\n@media (prefers-reduced-motion: reduce) {\n  :root, [data-theme] {\n';
for (const n of names.filter((n) => n.startsWith('motion.duration.'))) css += `    ${semVar(n)}: 0ms;\n`;
css += '  }\n}\n';

const resolvedThemes = {};
for (const t of themes) {
  const out = {};
  for (const n of names) out[n] = resolve(t.tokens[n] ?? semantic.tokens[n].value, `${t.name}.${n}`);
  resolvedThemes[t.name] = out;
}
// Every theme must pass every configured contrast pair (WCAG 2.2 SC 1.4.3 and 1.4.11); fail the build otherwise.
const contrastFailures = [];
for (const [themeName, values] of Object.entries(resolvedThemes)) {
  for (const p of semantic.contrastPairs) {
    const ratio = contrastRatio(values[p.fg], values[p.bg]);
    const need = contrastThreshold[p.kind];
    if (ratio === null) contrastFailures.push(`${themeName}: ${p.fg} on ${p.bg}: cannot check (${values[p.fg]} on ${values[p.bg]})`);
    else if (ratio < need) contrastFailures.push(`${themeName}: ${p.fg} on ${p.bg}: ${ratio.toFixed(2)}:1, needs ${need}:1 (${p.kind})`);
  }
}
if (contrastFailures.length) {
  console.error(`tokens: contrast check FAILED (${contrastFailures.length})\n` + contrastFailures.join('\n'));
  process.exit(1);
}

const meta = Object.fromEntries(names.map((n) => [n, { group: semantic.tokens[n].group, type: semantic.tokens[n].type, cssVar: semVar(n) }]));

const ts = `// Generated by scripts/build-tokens.mjs. Do not edit.
export const tokenNames = ${JSON.stringify(names, null, 2)} as const;
export type TokenName = (typeof tokenNames)[number];
export type TokenType = 'color' | 'font' | 'size' | 'number' | 'shadow' | 'duration' | 'easing';
export interface TokenMeta { group: string; type: TokenType; cssVar: string }
export const tokenMeta: Record<TokenName, TokenMeta> = ${JSON.stringify(meta, null, 2)};
/** CSS var() reference for a semantic token. */
export function v(name: TokenName): string {
  return \`var(\${tokenMeta[name].cssVar})\`;
}
export const themeNames = ${JSON.stringify(themes.map((t) => t.name))} as const;
export type ThemeName = (typeof themeNames)[number];
/** Theme values with primitive references resolved, for the theme editor. */
export const resolvedThemes: Record<ThemeName, Record<TokenName, string>> = ${JSON.stringify(resolvedThemes, null, 2)};
export interface ContrastPair { fg: TokenName; bg: TokenName; kind: 'text' | 'large' | 'ui' }
export const contrastPairs: ContrastPair[] = ${JSON.stringify(semantic.contrastPairs, null, 2)};
`;

writeFileSync(join(root, 'tokens.css'), css);
writeFileSync(join(root, 'tokens.ts'), ts);
console.log(`tokens: ${Object.keys(flat).length} primitives, ${names.length} semantic, themes: ${themes.map((t) => t.name).join(', ')}`);
